name: space_clicker
description: "Jeu clicker sur le thème de l'exploration spatiale."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.7
  sqflite_common_ffi: ^2.3.3

  # UI & icônes
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10

  # Gestion de l’état simple
  provider: ^6.1.2

  # Sauvegarde locale
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0

  # Sons
  audioplayers: ^5.2.1

  # Animations et responsive
  flutter_animate: ^4.5.0
  responsive_framework: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Ajoute ici tes éventuels assets (sons, images, etc.)
  assets:
    - assets/images/
    - assets/sounds/

  # Ajoute ici si tu as des polices
  # fonts:
  #   - family: Orbitron
  #     fonts:
  #       - asset: assets/fonts/Orbitron-Regular.ttf
